apiVersion: apps/v1
kind: Deployment
metadata:
  name: ultramarket-cart-service
  namespace: ultramarket-production
  labels:
    app: ultramarket-cart-service
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ultramarket-cart-service
  template:
    metadata:
      labels:
        app: ultramarket-cart-service
        version: v1
    spec:
      containers:
      - name: cart-service
        image: ghcr.io/ultramarket/cart-service:latest
        ports:
        - containerPort: 3003
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3003"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: ultramarket-secrets
              key: redis-url
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: ultramarket-secrets
              key: mongodb-url
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: ultramarket-cart-service
  namespace: ultramarket-production
  labels:
    app: ultramarket-cart-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3003
    protocol: TCP
    name: http
  selector:
    app: ultramarket-cart-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ultramarket-cart-service-hpa
  namespace: ultramarket-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ultramarket-cart-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15