groups:
  - name: ultramarket-alerts
    rules:
      # High CPU Usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: 'High CPU usage detected'
          description: 'CPU usage is above 80% for more than 5 minutes on instance {{ $labels.instance }}'

      # High Memory Usage
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: 'High memory usage detected'
          description: 'Memory usage is above 85% for more than 5 minutes on instance {{ $labels.instance }}'

      # High Disk Usage
      - alert: HighDiskUsage
        expr: 100 - ((node_filesystem_avail_bytes{mountpoint="/"} * 100) / node_filesystem_size_bytes{mountpoint="/"}) > 90
        for: 5m
        labels:
          severity: critical
          service: system
        annotations:
          summary: 'High disk usage detected'
          description: 'Disk usage is above 90% for more than 5 minutes on instance {{ $labels.instance }}'

      # Service Down
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          service: '{{ $labels.job }}'
        annotations:
          summary: 'Service is down'
          description: 'Service {{ $labels.job }} on instance {{ $labels.instance }} has been down for more than 1 minute'

      # High HTTP Error Rate
      - alert: HighHTTPErrorRate
        expr: rate(http_requests_total{status_code=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 10
        for: 5m
        labels:
          severity: warning
          service: api
        annotations:
          summary: 'High HTTP error rate detected'
          description: 'HTTP error rate is above 10% for more than 5 minutes on {{ $labels.instance }}'

      # High Response Time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          service: api
        annotations:
          summary: 'High response time detected'
          description: '95th percentile response time is above 1 second for more than 5 minutes on {{ $labels.instance }}'

      # Database Connection Pool Exhausted
      - alert: DatabaseConnectionPoolExhausted
        expr: pg_stat_activity_count > 90
        for: 2m
        labels:
          severity: critical
          service: database
        annotations:
          summary: 'Database connection pool exhausted'
          description: 'PostgreSQL connection pool is above 90% capacity for more than 2 minutes'

      # Redis Memory Usage High
      - alert: RedisMemoryUsageHigh
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 90
        for: 5m
        labels:
          severity: warning
          service: cache
        annotations:
          summary: 'Redis memory usage high'
          description: 'Redis memory usage is above 90% for more than 5 minutes'

      # Container Restart Rate High
      - alert: ContainerRestartRateHigh
        expr: rate(container_last_seen[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: container
        annotations:
          summary: 'Container restart rate high'
          description: 'Container {{ $labels.name }} is restarting frequently'

      # API Gateway Rate Limit Exceeded
      - alert: APIGatewayRateLimitExceeded
        expr: rate(http_requests_total{status_code="429"}[5m]) > 10
        for: 2m
        labels:
          severity: warning
          service: api-gateway
        annotations:
          summary: 'API Gateway rate limit exceeded'
          description: 'API Gateway is receiving too many requests and rate limiting is being triggered'

      # Queue Length High
      - alert: QueueLengthHigh
        expr: rabbitmq_queue_messages > 1000
        for: 5m
        labels:
          severity: warning
          service: messaging
        annotations:
          summary: 'Message queue length high'
          description: 'Message queue {{ $labels.queue }} has more than 1000 messages for more than 5 minutes'

      # SSL Certificate Expiry
      - alert: SSLCertificateExpiry
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
        for: 1h
        labels:
          severity: warning
          service: security
        annotations:
          summary: 'SSL certificate expiring soon'
          description: 'SSL certificate for {{ $labels.instance }} expires in less than 30 days'
