global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'noreply@ultramarket.com'
  smtp_auth_username: 'noreply@ultramarket.com'
  smtp_auth_password: 'your-app-password'
  smtp_require_tls: true

  # Slack webhook URL
  slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'

  # Telegram bot token and chat ID
  telegram_api_url: 'https://api.telegram.org/bot<YOUR_BOT_TOKEN>/sendMessage'

  # Global resolve timeout
  resolve_timeout: 5m

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Routing configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    # Critical alerts go to multiple channels
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      group_interval: 5m
      repeat_interval: 30m

    # Warning alerts go to Slack
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      group_interval: 10m
      repeat_interval: 2h

    # Database alerts
    - match:
        service: database
      receiver: 'database-alerts'
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 1h

    # Business alerts
    - match:
        team: business
      receiver: 'business-alerts'
      group_wait: 1m
      group_interval: 15m
      repeat_interval: 4h

# Receiver configurations
receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'admin@ultramarket.com'
        subject: 'UltraMarket Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@ultramarket.com,devops@ultramarket.com'
        subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        body: |
          🚨 CRITICAL ALERT 🚨

          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          Severity: {{ .Labels.severity }}
          Started: {{ .StartsAt }}
          {{ end }}

          Please investigate immediately!

    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts-critical'
        title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Service:* {{ .Labels.service }}
          *Instance:* {{ .Labels.instance }}
          *Severity:* {{ .Labels.severity }}
          {{ end }}
        color: 'danger'

    # Telegram notification for critical alerts
    webhook_configs:
      - url: 'https://api.telegram.org/bot<YOUR_BOT_TOKEN>/sendMessage'
        send_resolved: true
        http_config:
          proxy_url: ''
        title: '🚨 Critical Alert'
        text: |
          🚨 CRITICAL ALERT 🚨
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          {{ end }}

  - name: 'warning-alerts'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts-warning'
        title: '⚠️ Warning: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Service:* {{ .Labels.service }}
          *Instance:* {{ .Labels.instance }}
          {{ end }}
        color: 'warning'

  - name: 'database-alerts'
    email_configs:
      - to: 'dba@ultramarket.com,devops@ultramarket.com'
        subject: '🗄️ Database Alert: {{ .GroupLabels.alertname }}'
        body: |
          🗄️ DATABASE ALERT 🗄️

          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Database: {{ .Labels.instance }}
          Severity: {{ .Labels.severity }}
          {{ end }}

    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts-database'
        title: '🗄️ Database Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Database:* {{ .Labels.instance }}
          {{ end }}
        color: '#FF9900'

  - name: 'business-alerts'
    email_configs:
      - to: 'business@ultramarket.com'
        subject: '📊 Business Alert: {{ .GroupLabels.alertname }}'
        body: |
          📊 BUSINESS ALERT 📊

          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Metric: {{ .Labels.alertname }}
          {{ end }}

    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts-business'
        title: '📊 Business Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Metric:* {{ .Labels.alertname }}
          {{ end }}
        color: '#0066CC'

# Inhibition rules
inhibit_rules:
  # Inhibit warning alerts if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

  # Inhibit duplicate alerts
  - source_match:
      alertname: 'ServiceDown'
    target_match:
      alertname: 'HighErrorRate'
    equal: ['instance']
