global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ultramarket-production'
    environment: 'production'

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Product Service
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Order Service
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3004']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Payment Service
  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:3005']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Notification Service
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3007']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Analytics Service
  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:3008']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Web App (Frontend)
  - job_name: 'web-app'
    static_configs:
      - targets: ['web-app:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Admin Panel
  - job_name: 'admin-panel'
    static_configs:
      - targets: ['admin-panel:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 15s
    scrape_timeout: 5s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # MongoDB
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongo:27017']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s

  # Elasticsearch
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # ClickHouse
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter (System metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    scrape_timeout: 5s

  # Blackbox Exporter (Uptime monitoring)
  - job_name: 'blackbox'
    static_configs:
      - targets:
        - 'https://ultramarket.uz'
        - 'https://api.ultramarket.uz'
        - 'https://admin.ultramarket.uz'
    metrics_path: '/probe'
    params:
      module: [http_2xx]
    scrape_interval: 60s
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  # Custom Business Metrics
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['analytics-service:3008']
    metrics_path: '/business-metrics'
    scrape_interval: 60s
    scrape_timeout: 15s

  # Payment Gateway Health Checks
  - job_name: 'payment-gateways'
    static_configs:
      - targets: ['payment-service:3005']
    metrics_path: '/gateway-health'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Database Performance Metrics
  - job_name: 'database-performance'
    static_configs:
      - targets: ['postgres:5432', 'mongo:27017', 'clickhouse:8123']
    metrics_path: '/performance-metrics'
    scrape_interval: 60s
    scrape_timeout: 15s

  # Cache Performance
  - job_name: 'cache-performance'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/cache-metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Search Performance
  - job_name: 'search-performance'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/search-metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # API Response Times
  - job_name: 'api-response-times'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/response-times'
    scrape_interval: 15s
    scrape_timeout: 5s

  # Error Rates
  - job_name: 'error-rates'
    static_configs:
      - targets: 
        - 'api-gateway:3000'
        - 'auth-service:3002'
        - 'product-service:3003'
        - 'order-service:3004'
        - 'payment-service:3005'
    metrics_path: '/error-metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # User Activity Metrics
  - job_name: 'user-activity'
    static_configs:
      - targets: ['analytics-service:3008']
    metrics_path: '/user-metrics'
    scrape_interval: 60s
    scrape_timeout: 15s

  # Order Processing Metrics
  - job_name: 'order-processing'
    static_configs:
      - targets: ['order-service:3004']
    metrics_path: '/order-metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Payment Processing Metrics
  - job_name: 'payment-processing'
    static_configs:
      - targets: ['payment-service:3005']
    metrics_path: '/payment-metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Notification Delivery Metrics
  - job_name: 'notification-delivery'
    static_configs:
      - targets: ['notification-service:3007']
    metrics_path: '/notification-metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Frontend Performance
  - job_name: 'frontend-performance'
    static_configs:
      - targets: ['web-app:80', 'admin-panel:80']
    metrics_path: '/performance'
    scrape_interval: 60s
    scrape_timeout: 15s

  # Security Metrics
  - job_name: 'security-metrics'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/security-metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Resource Usage
  - job_name: 'resource-usage'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Network Performance
  - job_name: 'network-performance'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/network-metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # SSL Certificate Monitoring
  - job_name: 'ssl-certificates'
    static_configs:
      - targets:
        - 'https://ultramarket.uz'
        - 'https://api.ultramarket.uz'
        - 'https://admin.ultramarket.uz'
    metrics_path: '/probe'
    params:
      module: [ssl_2xx]
    scrape_interval: 3600s  # Check SSL certificates every hour
    scrape_timeout: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
