global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ultramarket-uzbekistan'
    region: 'uzbekistan'
    timezone: 'Asia/Tashkent'

rule_files:
  - 'alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # ===========================================
  # CORE INFRASTRUCTURE MONITORING
  # ===========================================

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - 'localhost:9100'
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s
    metrics_path: /metrics

  # ===========================================
  # MICROSERVICES MONITORING
  # ===========================================

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'api-gateway'

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'auth-service'

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3002']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'user-service'

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:3003']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'product-service'

  - job_name: 'cart-service'
    static_configs:
      - targets: ['cart-service:3004']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'cart-service'

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3005']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'order-service'

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:3012']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'payment-service'

  - job_name: 'shipping-service'
    static_configs:
      - targets: ['shipping-service:3011']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'shipping-service'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3006']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'search-service'
    static_configs:
      - targets: ['search-service:3007']
    scrape_interval: 15s
    metrics_path: /metrics

  # ===========================================
  # UZBEKISTAN-SPECIFIC MONITORING
  # ===========================================

  - job_name: 'uzbek-payment-systems'
    static_configs:
      - targets: ['payment-service:3012']
    scrape_interval: 30s
    metrics_path: /metrics/uzbek-payments
    params:
      systems: ['click', 'payme', 'uzcard', 'humo']

  - job_name: 'uzbek-delivery-providers'
    static_configs:
      - targets: ['shipping-service:3011']
    scrape_interval: 60s
    metrics_path: /metrics/uzbek-shipping
    params:
      providers: ['express24', 'uzpost', 'yandex', 'local']

  - job_name: 'uzbek-regions-performance'
    static_configs:
      - targets: ['analytics-service:3015']
    scrape_interval: 300s # 5 minutes
    metrics_path: /metrics/regions
    params:
      regions: ['TSH', 'SAM', 'BUX', 'AND', 'FAR', 'NAM']

  # ===========================================
  # BUSINESS METRICS MONITORING
  # ===========================================

  - job_name: 'business-metrics'
    static_configs:
      - targets: ['analytics-service:3015']
    scrape_interval: 60s
    metrics_path: /metrics/business
    params:
      currency: ['UZS']
      timezone: ['Asia/Tashkent']

  - job_name: 'uzs-conversion-rates'
    static_configs:
      - targets: ['api-gateway:3000']
    scrape_interval: 3600s # 1 hour
    metrics_path: /metrics/currency
    params:
      base: ['UZS']
      targets: ['USD', 'EUR', 'RUB']

  # ===========================================
  # FRONTEND MONITORING
  # ===========================================

  - job_name: 'web-app-metrics'
    static_configs:
      - targets: ['web-app:3100']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'admin-panel-metrics'
    static_configs:
      - targets: ['admin-panel:3101']
    scrape_interval: 30s
    metrics_path: /metrics

  # ===========================================
  # EXTERNAL SERVICES MONITORING
  # ===========================================

  - job_name: 'click-api-health'
    static_configs:
      - targets: ['api.click.uz:443']
    scrape_interval: 300s
    metrics_path: /health
    scheme: https
    relabel_configs:
      - source_labels: [__address__]
        target_label: external_service
        replacement: 'click-uz'

  - job_name: 'payme-api-health'
    static_configs:
      - targets: ['checkout.paycom.uz:443']
    scrape_interval: 300s
    metrics_path: /health
    scheme: https
    relabel_configs:
      - source_labels: [__address__]
        target_label: external_service
        replacement: 'payme-uz'

  - job_name: 'express24-api-health'
    static_configs:
      - targets: ['api.express24.uz:443']
    scrape_interval: 300s
    scheme: https
    relabel_configs:
      - source_labels: [__address__]
        target_label: external_service
        replacement: 'express24'

  # ===========================================
  # SECURITY MONITORING
  # ===========================================

  - job_name: 'fail2ban-exporter'
    static_configs:
      - targets: ['fail2ban-exporter:9191']
    scrape_interval: 60s
    metrics_path: /metrics

  - job_name: 'ssl-exporter'
    static_configs:
      - targets: ['ssl-exporter:9219']
    scrape_interval: 3600s # 1 hour
    params:
      target:
        - 'https://ultramarket.uz'
        - 'https://api.ultramarket.uz'
        - 'https://admin.ultramarket.uz'

  # ===========================================
  # CUSTOM UZBEKISTAN METRICS
  # ===========================================

  - job_name: 'uzbek-business-hours'
    static_configs:
      - targets: ['api-gateway:3000']
    scrape_interval: 300s
    metrics_path: /metrics/business-hours
    params:
      timezone: ['Asia/Tashkent']
      hours: ['09:00-22:00']

  - job_name: 'uzbek-language-usage'
    static_configs:
      - targets: ['analytics-service:3015']
    scrape_interval: 600s # 10 minutes
    metrics_path: /metrics/languages
    params:
      languages: ['uz', 'ru', 'en']

  - job_name: 'uzbek-phone-validation'
    static_configs:
      - targets: ['user-service:3002']
    scrape_interval: 60s
    metrics_path: /metrics/phone-validation
    params:
      operators: ['ucell', 'beeline', 'uzmobile']

# ===========================================
# REMOTE WRITE CONFIGURATION
# ===========================================

remote_write:
  - url: 'http://victoriametrics:8428/api/v1/write'
    queue_config:
      max_samples_per_send: 10000
      batch_send_deadline: 5s
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'uzbek_.*|ultramarket_.*'
        target_label: __name__
        replacement: '${1}'
