apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ultramarket
type: Opaque
data:
  password: dWx0cmFtYXJrZXRfcGFzc3dvcmQ= # ultramarket_password (base64)
  url: cG9zdGdyZXNxbDovL3VsdHJhbWFya2V0X3VzZXI6dWx0cmFtYXJrZXRfcGFzc3dvcmRAcG9zdGdyZXMtc2VydmljZTo1NDMyL3VsdHJhbWFya2V0 # postgresql://ultramarket_user:ultramarket_password@postgres-service:5432/ultramarket
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: ultramarket
type: Opaque
data:
  password: dWx0cmFtYXJrZXRfcGFzc3dvcmQ= # ultramarket_password
  url: bW9uZ29kYjovL3VsdHJhbWFya2V0X2FkbWluOnVsdHJhbWFya2V0X3Bhc3N3b3JkQG1vbmdvZGItc2VydmljZToyNzAxNy91bHRyYW1hcmtldF9wcm9kdWN0cz9hdXRoU291cmNlPWFkbWlu # mongodb://ultramarket_admin:ultramarket_password@mongodb-service:27017/ultramarket_products?authSource=admin
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: ultramarket
type: Opaque
data:
  password: dWx0cmFtYXJrZXRfcGFzc3dvcmQ= # ultramarket_password
  url: cmVkaXM6Ly86dWx0cmFtYXJrZXRfcGFzc3dvcmRAcmVkaXMtc2VydmljZTo2Mzc5 # redis://:ultramarket_password@redis-service:6379
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: ultramarket
type: Opaque
data:
  secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1mb3ItcHJvZHVjdGlvbi11bHRyYW1hcmtldA== # your-super-secret-jwt-key-for-production-ultramarket
  refresh-secret: eW91ci1zdXBlci1zZWNyZXQtand0LXJlZnJlc2gta2V5LWZvci1wcm9kdWN0aW9uLXVsdHJhbWFya2V0 # your-super-secret-jwt-refresh-key-for-production-ultramarket
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
  namespace: ultramarket
type: Opaque
data:
  url: aHR0cDovL2VsYXN0aWNzZWFyY2gtc2VydmljZTo5MjAw # http://elasticsearch-service:9200
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
  namespace: ultramarket
type: Opaque
data:
  brokers: a2Fma2Etc2VydmljZTo5MDky # kafka-service:9092
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
  namespace: ultramarket
type: Opaque
data:
  secret-key: c2tfdGVzdF95b3VyX3N0cmlwZV90ZXN0X2tleQ== # sk_test_your_stripe_test_key
  webhook-secret: d2hzZWNfeW91cl9zdHJpcGVfd2ViaG9va19zZWNyZXQ= # whsec_your_stripe_webhook_secret
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: ultramarket-monitoring
type: Opaque
data:
  admin-password: YWRtaW4xMjM= # admin123
---
apiVersion: v1
kind: Secret
metadata:
  name: ultramarket-tls
  namespace: ultramarket
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0= # Your SSL certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0= # Your SSL private key
